### PR TITLE
French dictionary

### PR DESCRIPTION
**Pull request by darwiin**
Add french dictionnary from french-badwords-list as an option. 

Come with unit tests on the methods added.

### CODE REVIEW

**Comment by jojoee** [comment]
@darwiin look good, but I might need to tweak the code a little bit.
Are you ok with that ?

**Comment by darwiin** [comment]
Sure @jojoee let me know when it's done ;). Do you plan to keep using my module french-badwords-list ?

**Comment by jojoee** [comment]
Ok, the thing is I don't understand the language much but I will.

**Pull request merged**
